version: "3"

services:
    web:
      build: .
      command: npm run start
      environment: 
          - MONGO_PASSWORD=${MONGO_PASSWORD}
          - JWT_SECRET=${JWT_SECRET}
      ports: 
          - "4000:4000"
      restart: unless-stopped