version: "3"

services:
    web:
      build: .
      command: npm run start
      environment: 
          - MONGO_PASSWORD=${MONGO_PASSWORD}
          - JWT_SECRET=${JWT_SECRET}
          - AWS_REGION=${AWS_REGION}
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      ports: 
          - "4000:4000"
      restart: unless-stopped